CREATE TABLE `ACT_RE_LANG`  (
  `ID_` varchar(64) NOT NULL,
  `PROCESS_ID_` varchar(64) NULL DEFAULT NULL,
  `PROCESS_NAME_` varchar(255) NULL DEFAULT NULL,
  `LANG_` varchar(255) NULL DEFAULT NULL,
  `DEPLOYMENT_INFO_` varchar(4000) NULL DEFAULT NULL,
  `CREATE_TIME_` timestamp NULL DEFAULT NULL,
  `LAST_UPDATE_TIME_` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID_`) USING BTREE
);